# Generated by Django 5.2.9 on 2026-02-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='encrypted_content',
            field=models.BinaryField(blank=True, null=True, verbose_name='加密内容'),
        ),
    ]
