# Generated by Django 5.2.9 on 2026-02-16 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_privatemessage_encrypted_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatemessage',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveIndex(
            model_name='privatemessage',
            name='blog_privat_sender__283565_idx',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='content',
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='burn_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='定时销毁时间'),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='destroyed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际销毁时间'),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='encryption_type',
            field=models.CharField(choices=[('system', '系统加密'), ('custom', '用户自定义加密')], default='system', max_length=10, verbose_name='加密类型'),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='is_burn_after_reading',
            field=models.BooleanField(default=False, verbose_name='阅后即焚'),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_private_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_private_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='blog.privatechatsession'),
        ),
        migrations.AddIndex(
            model_name='privatemessage',
            index=models.Index(fields=['burn_at'], name='blog_privat_burn_at_1fdf7e_idx'),
        ),
    ]
